name: aquatx-srna
channels:
  - bioconda
dependencies:
  - python>=3.7
  - numpy==1.19.2
  - pandas==1.2.1
  - matplotlib==3.3.2
  - fastp==0.20.1
  - bowtie>=1.2.3
  - nodejs>=10.13.0
  - pip
  - pip:
      - htseq
      - psutil
      - . # This allows pip to handle the installation of AQuATx via setup.py